# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "merqury"
description: Merqury is a tool for genome quality assessment that uses k-mer counts from raw sequencing data to evaluate the accuracy and completeness of a genome assembly. Meryl is the companion tool that efficiently counts and stores k-mers from sequencing reads, enabling Merqury to estimate metrics like assembly completeness and base accuracy. These tools provide a k-mer-based approach to assess assembly quality, helping to identify potential errors or gaps.​
keywords:
  - assembly
  - qc
  - kmer
components:
  - meryl/count
  - meryl/unionsum
  - merqury/merqury
## TODO nf-core: List all of the channels used as input with a description and their structure
input:
  - fastq:
      type: file
      description: |
        The input channel containing the fastq files
        Structure: [ val(meta), path(fastq) ]
      pattern: "*.{fastq/fastq.gz/fq/fq.gz}"
## TODO: fastq, kvalue
## TODO nf-core: List all of the channels used as output with a descriptions and their structure
output:
  - bam:
      type: file
      description: |
        Channel containing BAM files
        Structure: [ val(meta), path(bam) ]
      pattern: "*.bam"
  - bai:
      type: file
      description: |
        Channel containing indexed BAM (BAI) files
        Structure: [ val(meta), path(bai) ]
      pattern: "*.bai"
  - csi:
      type: file
      description: |
        Channel containing CSI files
        Structure: [ val(meta), path(csi) ]
      pattern: "*.csi"
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@stephenturner"
maintainers:
  - "@stephenturner"
